### ISSUE TITLE
chained variables in postgres data source in grafana

### ISSUE THREAD

**Issue by Bharath4297** [torkelo/dashboards#14]
[](url)Hello @torkelo 

I am using prometheus and postgres as data sources.
In postgres I am using IP, Team, Owner, and Os as attributes.
I am scraping node exporter metrics through prometheus. I want to filter through teams. like If I select one team I have to get owner, ip address and node exporter metrics too.. similarly If I select all option in team variable I have to get all teams details and each teams have to display owner ip and node exporter metrics. But I am facing issue with all option

Owner and IP are dependent on team. I declared variables as follows:

team: select team from server;
owner: select owner from server where team=$team;
ip: select ip from server where team=$team;

below pics are the data which I am getting. could you please help me? if I select all option I am getting only postgres data I am not getting prometheus data.
![Screenshot (138)](https://user-images.githubusercontent.com/94895356/156745865-2ee5d60b-6377-4961-a9e3-80a36cfb753a.png)
![Screenshot (139)](https://user-images.githubusercontent.com/94895356/156745874-6d0e2259-92d0-4776-a30e-a18eb8f292bf.png)

**Comment by torkelo** [comment]
> below pics are the data which I am getting. could you please help me? if I select all option I am getting only postgres data I am not getting prometheus data.

I have no way to help you with only that info. "I am not getting prometheus data", is not a lot to go on.Your screenshots show data. What data is not being queried / shown? Can you show the query and query results? what requests are issued, what are the responses?
